#%RAML 1.0 Trait

usage: |
  To be applied to endpoints that support date based conditional requests as 
  described in [conditional requests](https://confluence.internal.salesforce.com/display/ENG/RESTful+APIs+Conventions+and+Standards+v1.1).
  Parameters:
    - `responseStatus` (integer): |
      The status this endpoint will return. Iif there are multiple statutes with this purpose 
      in the endpoint, this trait won't be a good option.

headers: 
  If-Modified-Since:
    description: The server will return the requested resource only if it has been last modified after the given date
    required: false
    examples: 
      92-olimpics: Sat, 25 Jul 1992 19:00:00 GMT

responses: 
  <<responseStatus>>:
    description: The requested resource
  304:
    description: The resource has not been modified since the requested conditional date
