#%RAML 1.0 NamedExample
value: 
  [
    {
      "id" : "tiles", 
      "components" : [
        {
          "id" : "w3reö9wsjf3",
          "typeId" : "commerce_assets.productTile",
          "data" : {
            "product" : "iphone6"
          }
        },
        {
          "id" : "cgn8d4ngdl4n",
          "typeId" : "commerce_assets.productTile",
          "data" : {
            "product" : "iphone7"
          }
        }
      ]
    }
  ]