#%RAML 1.0 NamedExample
value: 
  [
    {
      "id" : "iofwj38fhw3f", 
      "typeId" : "commerce_assets.banner", 
      "data" : {
        "title" : "Products On Sale", 
        "bannerImage" : "sale/topsellerPromo.jpg"
      }, 
      "custom" : {
        "thumbnail_full" : "http://static.myshop.com/sale/topsellerPromo.jpg"
      }
    }
  ]