arrowParens: 'always'
bracketSpacing: false
printWidth: 100
singleQuote: true
semi: false
tabWidth: 4
overrides:
  - files: '*.json'
    options:
      tabWidth: 2
  - files: '*.yml'
    options:
      tabWidth: 2
  - files: '*.yaml'
    options:
      tabWidth: 2
