#%RAML 1.0 NamedExample
MultipleOperatorExample:
  must:
    - textQuery:
        fields:
          - couponId
        searchPhrase: DEAL
  should:
    - textQuery:
        fields:
          - couponId
        searchPhrase: DEAL
    - textQuery:
        fields:
          - couponId
          - description
        searchPhrase: sale
  must_not:
    - textQuery:
        fields:
          - description
        searchPhrase: Big bargain
AndOperatorExample:
  must:
    - textQuery:
        fields:
          - couponId
        searchPhrase: DEAL
    - termQuery:
        fields:
          - enabled
        operator: is
        values:
          - true
OrOperatorExample:
  should:
    - textQuery:
        fields:
          - couponId
        searchPhrase: DEAL
    - textQuery:
        fields:
          - couponId
          - description
        searchPhrase: sale
NotOperatorExample:
  must_not:
    - textQuery:
        fields:
          - description
        searchPhrase: Big bargain
    - termQuery:
        fields:
          - enabled
        operator: is
        values:
          - false     