#%RAML 1.0 NamedExample

value:
  {
    "recentSearchPhrases": [],
    "suggestedSearchPhrases": [
        {
            "phrase": "camera"
        }
    ],
    "popularSearchPhrases": [
        {
            "phrase": "canon"
        },
        {
            "phrase": "camera"
        },
        {
            "phrase": "nikon"
        },
        {
            "phrase": "trouser"
        },
        {
            "phrase": "shorts"
        },
        {
            "phrase": "shirt"
        }
    ]
}