#%RAML 1.0 NamedExample
value:
  {
      "bonusProducts": [
          {
              "link": "bonus product link",
              "productDescription": "Bonus Product",
              "productId": "34984327448",
              "productName": "Extra Fluffy Bonus Product",
              "title": "Bonus Product"
          }
      ],
      "couponCode": "BONUS",
      "id": "qhegj345ruhrfkj",
      "maxBonusItems": 1,
      "promotionId": "basds98295jsafi"
  }
