#%RAML 1.0 NamedExample
value:
  {
   
    "authenticationProviderId": "Google",
    "firstName" : "John",
    "lastName" : "Doe",
    "email": "testCustomer@test.com",
    "externalId": "testCustomer@test.com"
  }