#%RAML 1.0 NamedExample
value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/invalid-operation",
    "detail": "Thrown when a start date but no end date was given, when an end date but no start date was given, or when the given end date is before the given start date",
    "title": "Incorrect Syntax"
  }