#%RAML 1.0 Library

#  To be applied on endpoints that use offset and limit pagination controls as described in [pagination controls](https://confluence.internal.salesforce.com/display/ENG/RESTful+APIs+Conventions+and+Standards+v1.1).
#
#  These are available separately as data types as they are sometimes referenced in the body of requests. In that case, it is recommended to override the maximum and the description of the limit to display the actual maximum allowed, possibly with a parameter as done in the offset-paginated trait. 

types:
  offset: 
    description: Used to retrieve the results based on a particular resource offset.
    type: integer
    format: int64
    default: 0
    minimum: 0
  limit: 
    description: Maximum records to retrieve per request, not to exceed the maximum defined. A limit must be at least 1 so at least one record is returned (if any match the criteria).
    type: integer
    format: int32
    default: 10
    minimum: 1
  total:
    description: The total number of hits that match the search's criteria. This can be greater than the number of results returned as search results are pagenated.
    type: integer
    format: int64
    default: 0
    minimum: 0