#%RAML 1.0 Library
usage: Use the following traits for request and response status information.

uses:
  ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.13/api-standards.raml

traits:
  NotFound: !include Traits/NotFoundException.raml
