#%RAML 1.0 Trait
description: This trait represents API behavior for a 400 response.
responses:
  400:
    description: Bad Request.
    body:
      application/problem+json:
        type: ErrorResponse
        example: |
          {
            "title": "Bad Request",
            "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/validation",
            "detail": "Maximum number of products you can request in one call is 25."
          }