#%RAML 1.0 Library
usage:

types:

  Region: 
    description: Region in which the service is exposed.
    example: en-US

  Version:
    description: The version of the commerce cloud API.
    example: v2