#%RAML 1.0 Library

types:
  
  CreationDateTime:
    description: The date time the resource was created.
    type: datetime
    example: 2020-02-28T10:41:50Z

  LastUpdateDateTime:
    description: The date time when the resource was last modified.
    type: datetime
    example: 2020-02-27T06:13:07Z 