#%RAML 1.0 Library

types:
  
  DataSetId:
    description: The unique identifier of a Data Set resource.
    type: string
    maxLength: 256
    example: d4330450-df8a-439f-80f8-847ae3cb564f

  AttributeId:
    description: User defined unique identifier for a specific attribute.
    type: string
    maxLength: 256
    example: name