/*
 * Copyright (c) 2021, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
/**
 * This is a mock config to be used for unit tests
 *
 * By default, a generated project is a single-site and single-locale app
 * However, it can be extended to multi-site with multi-locale easily.
 * To ensure that feature work correctly, we test our code with multi-site config in mind, so we created this mock config.
 * A single-site, single-locale config is a special case of multi-site case.
 */
module.exports = {
    app: {
        url: {
            locale: 'path',
            site: 'path',
            showDefaults: true
        },
        siteAliases: {
            'site-1': 'uk',
            'site-2': 'us'
        },
        defaultSite: 'site-1',
        sites: [
            {
                id: 'site-1',
                l10n: {
                    defaultLocale: 'en-GB',
                    defaultCurrency: 'GBP',
                    supportedLocales: [
                        {
                            id: 'en-GB',
                            preferredCurrency: 'GBP'
                        },
                        {
                            id: 'fr-FR',
                            alias: 'fr',
                            preferredCurrency: 'EUR'
                        },
                        {
                            id: 'it-IT',
                            preferredCurrency: 'EUR'
                        }
                    ]
                }
            },
            {
                id: 'site-2',
                l10n: {
                    defaultLocale: 'en-US',
                    defaultCurrency: 'USD',
                    supportedLocales: [
                        {
                            id: 'en-US',
                            preferredCurrency: 'USD'
                        },
                        {
                            id: 'en-CA',
                            preferredCurrency: 'USD'
                        }
                    ]
                }
            }
        ],
        commerceAPI: {
            proxyPath: `/mobify/proxy/api`,
            parameters: {
                clientId: 'c9c45bfd-0ed3-4aa2-9971-40f88962b836',
                organizationId: 'f_ecom_zzrf_001',
                shortCode: '11111111',
                siteId: 'site-1'
            }
        },
        einsteinAPI: {
            host: 'localhost:7777',
            einsteinId: '11111111',
            // This differs from the siteId in commerceAPIConfig for testing purposes
            siteId: 'EinsteinTestSite',
            // Flag Einstein activities as coming from a production environment.
            // By setting this to true, the Einstein activities generated by the environment will appear
            // in production environment reports
            // This is temporary and is meant as a placeholder until there is a mechanism for reading
            // the is_production property from an MRT target
            isProduction: false
        }
    },
    // This list contains server-side only libraries that you don't want to be compiled by webpack
    externals: [],
    // Page not found url for your app
    pageNotFoundURL: '/page-not-found',
    // Enables or disables building the files necessary for server-side rendering.
    ssrEnabled: true,
    // This list determines which files are available exclusively to the server-side rendering system
    // and are not available through the /mobify/bundle/ path.
    ssrOnly: ['ssr.js', 'ssr.js.map', 'node_modules/**/*.*'],
    // This list determines which files are available to the server-side rendering system
    // and available through the /mobify/bundle/ path.
    ssrShared: [
        'static/ico/favicon.ico',
        'static/robots.txt',
        '**/*.js',
        '**/*.js.map',
        '**/*.json'
    ],
    // Additional parameters that configure Express app behavior.
    ssrParameters: {
        ssrFunctionNodeVersion: '18.x',
        proxyConfigs: [
            {
                host: 'localhost:8888',
                path: 'api'
            },
            {
                host: 'localhost:9999',
                path: 'ocapi'
            }
        ]
    }
}
