#%RAML 1.0 NamedExample
value: 
  {
    "brand": "Apple",
    "currency": "USD",
    "id": "apple-ipod-shuffle",
    "imageGroups": [
        {
            "images": [
                {
                    "alt": "Apple iPod Shuffle, , large",
                    "link": "https://example.com/on/demandware.static/-/Sites-electronics-catalog/default/dwc2cc65b0/images/large/ipod-shuffle-silver.jpg",
                    "title": "Apple iPod Shuffle, "
                }
            ],
            "viewType": "large"
        },
        {
            "images": [
                {
                    "alt": "Apple iPod Shuffle, , medium",
                    "link": "https://example.com/on/demandware.static/-/Sites-electronics-catalog/default/dw5f36aab1/images/medium/ipod-shuffle-silver.jpg",
                    "title": "Apple iPod Shuffle, "
                }
            ],
            "viewType": "medium"
        },
        {
            "images": [
                {
                    "alt": "Apple iPod Shuffle, , small",
                    "link": "https://example.com/on/demandware.static/-/Sites-electronics-catalog/default/dw2b078e02/images/small/ipod-shuffle-silver.jpg",
                    "title": "Apple iPod Shuffle, "
                }
            ],
            "viewType": "small"
        }
    ],
    "inventory": {
        "ats": 0,
        "backorderable": false,
        "id": "SiteGenesisList",
        "orderable": true,
        "preorderable": false,
        "stockLevel": 999999
    },
    "longDescription": "Supports AAC, protected AAC, MP3, MP3 VBR, Audible, WAV and AIFF for immediate playback of multiple formats.",
    "master": {
        "masterId": "apple-ipod-shuffle",
        "orderable": false,
        "price": 45.99
    },
    "minOrderQuantity": 1,
    "name": "Apple iPod Shuffle",
    "pageDescription": "With the same size circular control pad as the previous model on a much more compact case with a built-in clip, the updated shuffle is ready to rock and easily tags along when you're on the go.",
    "pageKeywords": "Apple, iPod, Shuffle, MP3, Music Player",
    "pageTitle": "Apple iPod Shuffle",
    "price": 45.99,
    "priceMax": 69,
    "primaryCategoryId": "electronics-digital-media-players",
    "shortDescription": "With the same size circular control pad as the previous model on a much more compact case with a built-in clip, the updated shuffle is ready to rock and easily tags along when you're on the go.",
    "stepQuantity": 1,
    "type": {
        "master": true
    },
    "variants": [
        {
            "orderable": true,
            "price": 45.99,
            "productId": "apple-ipod-shuffle-silver-1g",
            "variationValues": {
                "color": "Silver",
                "memorySize": "1 GB"
            }
        },
        {
            "orderable": true,
            "price": 49,
            "productId": "apple-ipod-shuffle-blue-1g",
            "variationValues": {
                "color": "Blue",
                "memorySize": "1 GB"
            }
        },
        {
            "orderable": true,
            "price": 49,
            "productId": "apple-ipod-shuffle-green-1g",
            "variationValues": {
                "color": "Green",
                "memorySize": "1 GB"
            }
        },
        {
            "orderable": true,
            "price": 49,
            "productId": "apple-ipod-shuffle-red-1g",
            "variationValues": {
                "color": "Red",
                "memorySize": "1 GB"
            }
        },
        {
            "orderable": true,
            "price": 49,
            "productId": "apple-ipod-shuffle-fuscia-1g",
            "variationValues": {
                "color": "Fuscia",
                "memorySize": "1 GB"
            }
        },
        {
            "orderable": true,
            "price": 60,
            "productId": "apple-ipod-shuffle-silver-2g",
            "variationValues": {
                "color": "Silver",
                "memorySize": "2 GB"
            }
        },
        {
            "orderable": true,
            "price": 69,
            "productId": "apple-ipod-shuffle-green-2g",
            "variationValues": {
                "color": "Green",
                "memorySize": "2 GB"
            }
        },
        {
            "orderable": true,
            "price": 60,
            "productId": "apple-ipod-shuffle-red-2g",
            "variationValues": {
                "color": "Red",
                "memorySize": "2 GB"
            }
        },
        {
            "orderable": true,
            "price": 69,
            "productId": "apple-ipod-shuffle-fuscia-2g",
            "variationValues": {
                "color": "Fuscia",
                "memorySize": "2 GB"
            }
        }
    ],
    "variationAttributes": [
        {
            "id": "color",
            "name": "Color",
            "values": [
                {
                    "name": "Silver",
                    "orderable": false,
                    "value": "Silver"
                },
                {
                    "name": "Blue",
                    "orderable": false,
                    "value": "Blue"
                },
                {
                    "name": "Green",
                    "orderable": false,
                    "value": "Green"
                },
                {
                    "name": "Red",
                    "orderable": false,
                    "value": "Red"
                },
                {
                    "name": "Fuscia",
                    "orderable": false,
                    "value": "Fuscia"
                }
            ]
        },
        {
            "id": "memorySize",
            "name": "Memory Size",
            "values": [
                {
                    "name": "1 GB",
                    "orderable": true,
                    "value": "1 GB"
                },
                {
                    "name": "2 GB",
                    "orderable": true,
                    "value": "2 GB"
                }
            ]
        }
    ]
  }