name: setup_ubuntu
inputs:
  cwd:
    required: false
    default: ${{ github.workspace }}
  node:
    required: true
  npm:
    required: false
  update_npm:
    required: false
    default: false
description: "Setup Ubuntu Machine"
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: npm

    - name: Update NPM version
      if: inputs.update_npm == true
      run: |-
        npm install -g npm@${{ inputs.npm }}
      shell: bash

    - name: Install Dependencies
      working-directory: ${{ inputs.cwd }}
      run: |-
        # Install node dependencies
        echo ${{ inputs.update_npm }}
        node -v
        npm -v
        node ./scripts/gtime.js monorepo_install npm ci

        # Install Snyk CLI
        # TODO: Ticket W-12425059. Revisit Snyk CLI integration to monitor manifest files on generated projects.
        # TODO: Latest Snyk CLI version is currently failing on npm i. We use the alternative Snyk GitHub integration.
        # sudo npm install -g snyk

      shell: bash
