name: setup_ubuntu
inputs:
  cwd:
    required: false
    default: ${{ github.workspace }}
description: "Setup Ubuntu Machine"
runs:
  using: composite
  steps:
    - name: Install Dependencies
      working-directory: ${{ inputs.cwd }}
      run: |-
        # Install system dependencies
        sudo apt-get update -yq
        sudo apt-get install python2 python3-pip time -yq
        sudo pip install -U pip setuptools
        sudo pip install awscli==1.18.85 datadog==0.40.1

        # Install node dependencies
        node ./scripts/gtime.js monorepo_install npm ci

        # Build the PWA
        npm run lerna -- run analyze-build --scope "@salesforce/retail-react-app"

        # Report bundle sizes
        node ./scripts/report-bundle-size.js

        # Install Snyk CLI
        # TODO: Ticket W-12425059. Revisit Snyk CLI integration to monitor manifest files on generated projects.
        # TODO: Latest Snyk CLI version is currently failing on npm i. We use the alternative Snyk GitHub integration.
        # sudo npm install -g snyk

        # Install Lighthouse CI CLI
        sudo npm install -g @lhci/cli
      shell: bash
