#%RAML 1.0 NamedExample

value:
  {
    "title": "Malformed Price Refinement",
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/malformed-price-refinement",
    "detail": "The price refinement '(0.500)' is malformed. Something similar to '(0..100)' was expected.",
    "malformedPrice": "(0.500)"
  }