#%RAML 1.0 NamedExample
value:
  {
  "title": "String Constraint Violation",
  "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/string-constraint-violation",
  "detail": "The string length constraint was violated by 'q'. The expected length is '(3..50)'.",
  "expected": "(3..50)",
  "parameter": "q"
  }