name: bundlesize
inputs:
  cwd:
    required: true
runs:
  using: composite
  steps:
  - name: Analyze build
    working-directory: ${{ inputs.cwd }}
    run: |-
        npm run analyze-build
    shell: bash

  - name: Report bundle size
    run: |-
        node ./scripts/report-bundle-size.js ${{ inputs.cwd }}/build
    shell: bash

  # TODO: is it possible to set size thresholds in the world of extensions?
  # - name: Check bundle size
  #   run: |-
  #       npm run test:max-file-size
  #   shell: bash
