name: bundle_size_test
inputs:
  cwd:
    required: true
runs:
  using: composite
  steps:
  - name: Analyze build
    working-directory: ${{ inputs.cwd }}
    run: |-
        npm run analyze-build
    shell: bash

  - name: Check bundle sizes
    working-directory: ${{ inputs.cwd }}
    run: |-
        npx bundlesize -f "build/main.js" -s 10kB
        npx bundlesize -f "build/vendor.js" -s 390kB
    shell: bash

  - name: Report bundle sizes
    run: |-
        node ./scripts/report-bundle-size.js ${{ inputs.cwd }}/build
    shell: bash
