name: wait_for_mrt_deploy
inputs:
  TARGET:
    description: Runtime Admin target slug or environment id
    required: true
    type: string
  MRT_API_KEY:
    description: Runtime Admin user API_KEY
    required: true
    type: string
  VERSION:
    description: Git SHA of the version being deployed
    required: true
  PROJECT:
    description: Runtime Admin Project
    required: true
runs:
  using: composite
  steps:
    - name: Ping MRT to check if the latest bundle is deployed
      run: node e2e/scripts/wait-for-mrt-deploy.js --target ${{ inputs.TARGET }} --api-key ${{ inputs.MRT_API_KEY }} --version ${{ inputs.VERSION }} --project ${{ inputs.PROJECT }}
      shell: bash
