#%RAML 1.0 DocumentationItem
title: baseUri Standards
content: |

  # NOTE: this is internal documentation.

  The baseUri has been standardized as the following. You should use the below snippet in your RAML definitions:
          
      baseUri: https://{shortCode}.api.commercecloud.salesforce.com/api-family/api-name/{version}
      version: v1
      baseUriParameters:
        shortCode:
          description: A region-specific merchant identifier.
          example: 0dnz6oep
          pattern: ^([a-z0-9]+)(-[a-z0-9]+)*$

  Of note:
    - the baseUri is templated URL that is templated for constency, all URLs accross commerce cloud will have the same baseUrl
    - you MUST set the values of the api-family and api-name in the URI to your api-family and api-name.  These shouldn't ever change and should be in lower case kebab case
    - Api-family is also known as bounded context
    - Api-name is also known as root aggregate
    - the only baseUriParameter that will change between calls is `shortCode`.
      - `version` is special and will use the version of the API. 
