name: count_deps
inputs:
  project_dir:
    description: 'Path to the project directory'
    required: true
runs:
  using: composite
  steps:
  - name: Count Generated Project Dependencies
    # TODO: Can TOTAL_PACKAGES be exported in a cleaner way?
    run: |-
      MAX_PACKAGES="2260"
      total=$(./scripts/count-dependencies.js "${{ inputs.project_dir }}")
      echo "TOTAL_PACKAGES=${total}" >> $GITHUB_ENV

      if [ "$total" -gt "$MAX_PACKAGES" ]; then
          echo "Error: Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
          exit 1;
      else
          echo "Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
      fi
    shell: bash
