#%RAML 1.0 Trait
description: 401 response when a customer is not authorized.
responses:
  '401':
      description: |
                Indicates that the customerId URL parameter does not match the verified customer represented by the JWT token, which is not relevant when using OAuth, or indicates that the provided new address name is already used for the customer.
      body:
        application/problem+json:
          type: ErrorResponse
          example: |
            {
              "title": "Invalid Access Token",
              "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/invalid-access-token",
              "detail": "The request is unauthorized, the access token is invalid.",
              "accessToken": "iI6IjEiLCJhbGciOiJIUzI1NiIsInR5cCI6Ik"
            }