#%RAML 1.0 Library
usage: A common set of types used for describing the metadata of properties of types in the system, including both system and custom properties. 

uses:
  AdditionalProperties: additional-properties.raml
  ISO: ISO-standards.raml

types:
  AttributeDefinition:
    description: A collection of metadata describing the properties of a type. This can include properties that are provided by the system, and properties that are defined by the merchant to extend the base types.
    type:
      AdditionalProperties.NoPropertiesAllowed
    properties:
      defaultValue:
        description: 'The optional default value of this property.'
        type: PropertyValueDefinition
        required: false  
      id:
        description: The unique identifier for the property.
        type: string
        example: color
        required: false
        pattern: ^[A-Za-z0-9]+$
      name:
        description: The short, localized name of the definition, suitable for use in simple identifiers such as labels.
        type: ISO.L10nString
        properties:
        example:
          default: color
          de: fabre
      description:
        description: A localized description of the property, describing the property in detail.
        type: ISO.L10nString
        example: 
          default: The color of the product.
          de: Die Farbe des Produkts.
      key:
        description: A flag indicating if this property is part of the primary unique identifier of this type.
        type: boolean
        required: false
        default: false
        example: false
      localizable:
        description:  A flag indicating if this property supports localization.
        type: boolean
        required: false
        default: false
        example: false
      mandatory:
        description: A flag indicating if this property must be passed when creating or updating the type.
        type: boolean
        required: false
        default: false
        example: false
      max:
        description: If numeric, the maximum possible value for this property.
        type: number
        format: double
        required: false
        example: 100
      minLength:
        description: The minimum length of a value required when passing this property.
        type: integer
        format: int32
        required: false
        example: 5
      min:
        description: If numeric, the minimum possible value for this property.
        type: number
        format: double
        required: false
        example: 10
      multiValueType:
        description: A flag indicating if the property supports multiple values. Most property valueTypes only support one value. The valueTypes `int`, `double`, `string`,`enum_of_int` and `enum_of_string` may set this property to support multiple values.
        type: boolean
        required: false
        default: false
        example: false
      regularExpression:
        description: A regular expression that defines the valid values for this property. The exact regular expression syntax is determined by the implementation of the API. 
        type: string
        required: false
        example: ".*[a-zA-Z]{2,}+.*"
      scale:
        description: If the property supports floating point numbers, the number of decimal digits for a numeric value of this property.
        type: integer
        format: int32
        required: false
        default: 2
        example: 2
      searchable:
        description: A flag indicating if this property is intended to be indexed for searching in the customer facing storefront.
        type: boolean
        required: false
        default: false
        example: true
      siteSpecific:
        description: A flag indicating if this property supports different values for each storefront.
        type: boolean
        required: false
        default: false
        example: false
      system:
        description: A flag indicating if this property is provided by the system.
        type: boolean
        required: false
        default: false
        example: true
      unit:
        description: If numeric, identifes what unit of measure the value of this property is measured by.
        type: ISO.L10nString
        required: false
        example: 
          default: inches
          de: Zoll
      possibleValues:
        description: A set of values that are possible for this property.
        type: PropertyValueDefinition[]
        required: false
      type:
        description: The data type of this property.
        type: string
        enum:
          - string
          - int
          - double
          - text
          - html
          - date
          - image
          - boolean
          - money
          - quantity
          - datetime
          - email
          - password
          - enum_of_string
          - enum_of_int
        example: "string"
      visible:
        description: A flag indicating that this property is visible.
        type: boolean
        required: false
        default: true
        example: true
  PropertyValueDefinition:
    description: Represents an actual or possible value for a property
    type:
      AdditionalProperties.NoPropertiesAllowed   
    properties:
      description:
        description: A description of the property value.
        type: ISO.L10nString
        example:
          default: Rose Red
          de: Rosenrot
      displayValue:
        description: |-
          A display name that can be used to present this value in the user interface. For example, if the property is 'color', the value might be '1' but the display might  be 'Red'.
        type: ISO.L10nString
        example:
          default: Red
          de: Rot
      id:
        description: The unique id of the property value.
        type: string
        example: "1"
      position:
        description: The position of the property value within the collection of possible property values.
        type: number
        format: double
        required: false
        example: 0.0
      value:
        description: The value of the property.
        type: string 
        example: "1"