#%RAML 1.0 NamedExample
value:
  {
      "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/invalid-tax-mode",
      "title": "Invalid Tax Mode",
      "detail": "Basket with ID 'a10ff320829cb0eef93ca5310a' has invalid tax mode."
  }
