#%RAML 1.0 NamedExample
value:
  {
      "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unsupported-request-if-scapi-hooks-enabled",
      "title": "Unsupported Request If SCAPI Hooks Enabled",
      "detail": "You can't call this endpoint because Salesforce Commerce API hook execution is enabled."
  }
