#%RAML 1.0 NamedExample
value:
  {
    "taxes": {
        "3d4e28425ce0b3a65b0ac4e163":{
          "taxItems":[
              {
                "id":"DE_7",
                "rate":0.07,
                "value":13.99
              },
              {
                "id":"DE_19",
                "rate":0.19
              }
          ]
        },
        "ff9452ed11fcf5c80f9143a8f1":{
          "taxItems":[
              {
                "id":"US_1",
                "rate":0.01
              },
              {
                "id":"US_5",
                "rate":0.05
              }
          ]
        }
    }
  }