#%RAML 1.0 NamedExample
value:
  {
    "taxItems":[
      {
        "id":"DE_7",
        "rate":0.07,
        "value":13.99
      },
      {
        "id":"DE_19",
        "rate":0.19
      }
    ]
  }
