#%RAML 1.0 NamedExample
value:
  {
      "adjustedMerchandizeTotalTax": 30,
      "adjustedShippingTotalTax": 0.8,
      "agentBasket": false,
      "basketId": "a10ff320829cb0eef93ca5310a",
      "billingAddress": {
          "address1": "104 Presidential Way",
          "city": "Woburn",
          "countryCode": "US",
          "firstName": "Stephanie",
          "fullName": "Stephanie Miller",
          "id": "5f695b6f4bb63cb686483d65a0",
          "lastName": "Miller",
          "postalCode": "01801",
          "stateCode": "MA"
      },
      "channelType": "storefront",
      "couponItems": [
          {
              "code": "5ties",
              "couponItemId": "7800e0f611dac6caf77afb9df9",
              "statusCode": "no_applicable_promotion",
              "valid": true
          }
      ],
      "creationDate": "2019-10-17T08:53:30.993Z",
      "currency": "USD",
      "customerInfo": {
          "customerId": "beQeANXJNsd0xcINsB6cSrobQa",
          "email": "shopper@salesforce-test.com"
      },
      "lastModified": "2019-10-17T08:53:35.747Z",
      "merchandizeTotalTax": 30,
      "notes": {
      },
      "orderTotal": 646.76,
      "paymentInstruments": [
          {
              "amount": 0,
              "paymentCard": {
                  "cardType": "Visa",
                  "creditCardExpired": false
              },
              "paymentInstrumentId": "2b76b8644eb6da43e7e223b48d",
              "paymentMethodId": "CREDIT_CARD"
          }
      ],
      "productItems": [
          {
              "adjustedTax": 30,
              "basePrice": 199.99,
              "bonusProductLineItem": false,
              "gift": false,
              "itemId": "43c38652bc3844e14cd482ff28",
              "itemText": "Green Umbrella - Sustained Edition",
              "optionItems": [
                  {
                      "adjustedTax": 0,
                      "basePrice": 0,
                      "bonusProductLineItem": false,
                      "gift": false,
                      "itemId": "b4ff13039bc7abd1b9d933b871",
                      "itemText": "We will plant a tree for your order.",
                      "optionId": "plantATree",
                      "optionValueId": "000",
                      "price": 0,
                      "priceAfterItemDiscount": 0,
                      "priceAfterOrderDiscount": 0,
                      "productId": "000",
                      "productName": "Plant a tree.",
                      "quantity": 3,
                      "shipmentId": "me",
                      "tax": 0,
                      "taxBasis": 0,
                      "taxClassId": "standard",
                      "taxRate": 0.05
                  }
              ],
              "price": 599.97,
              "priceAfterItemDiscount": 599.97,
              "priceAfterOrderDiscount": 599.97,
              "productId": "green-umbrella",
              "productName": "Green Umbrella - Sustained Edition",
              "quantity": 3,
              "shipmentId": "me",
              "tax": 30,
              "taxBasis": 599.97,
              "taxClassId": "standard",
              "taxRate": 0.05
          }
      ],
      "productSubTotal": 599.97,
      "productTotal": 599.97,
      "shipments": [
          {
              "adjustedMerchandizeTotalTax": 30,
              "adjustedShippingTotalTax": 0.8,
              "gift": false,
              "merchandizeTotalTax": 30,
              "productSubTotal": 599.97,
              "productTotal": 599.97,
              "shipmentId": "me",
              "shipmentTotal": 646.76,
              "shippingAddress": {
                  "address1": "4162  Turkey Pen Road",
                  "city": "New York",
                  "countryCode": "US",
                  "firstName": "Agustin",
                  "fullName": "Agustin Estes",
                  "id": "193e99bc1205b870cebd36d970",
                  "lastName": "Estes",
                  "postalCode": "10016",
                  "stateCode": "NY"
              },
              "shippingMethod": {
                  "description": "Order received within 7-10 business days",
                  "id": "001",
                  "name": "Ground",
                  "price": 15.99
              },
              "shippingStatus": "not_shipped",
              "shippingTotal": 15.99,
              "shippingTotalTax": 0.8,
              "taxTotal": 30.8
          }
      ],
      "shippingItems": [
          {
              "adjustedTax": 0.8,
              "basePrice": 15.99,
              "itemId": "ac7a3b62dc1df8de898d7a2141",
              "itemText": "Shipping",
              "price": 15.99,
              "priceAfterItemDiscount": 15.99,
              "shipmentId": "me",
              "tax": 0.8,
              "taxBasis": 15.99,
              "taxClassId": "standard",
              "taxRate": 0.05
          }
      ],
      "shippingTotal": 15.99,
      "shippingTotalTax": 0.8,
      "taxation": "net",
      "taxTotal": 30.8,
      "c_textValue":"oak"
  }