#%RAML 1.0 NamedExample
value:
  {
      "adjustedMerchandizeTotalTax": 36.5,
      "adjustedShippingTotalTax": 0.8,
      "agentBasket": false,
      "basketId": "a10ff320829cb0eef93ca5310a",
      "billingAddress": {
          "address1": "4 Main St.",
          "address2": "Basement Flat",
          "city": "Boston",
          "companyName": "Flexo",
          "countryCode": "US",
          "firstName": "John",
          "fullName": "John H. Smith",
          "id": "0aa3fce01dec8a51ee50323c9c",
          "jobTitle": "Bug Fixer",
          "lastName": "Smith",
          "phone": "+1 33-33-33",
          "postalCode": "40982",
          "secondName": "H.",
          "stateCode": "MA",
          "title": "Mr"
      },
      "channelType": "storefront",
      "creationDate": "2019-10-17T10:59:24.503Z",
      "currency": "USD",
      "customerInfo": {
          "customerId": "beQeANXJNsd0xcINsB6cSrobQa",
          "email": ""
      },
      "giftCertificateItems": [
          {
              "amount": 2,
              "giftCertificateItemId": "a9c38be81002962a93310ffd66",
              "recipientEmail": "benet@example.com",
              "shipmentId": "me"
          }
      ],
      "lastModified": "2019-10-17T11:00:22.545Z",
      "merchandizeTotalTax": 36.5,
      "notes": {
      },
      "orderTotal": 785.24,
      "paymentInstruments": [
          {
              "amount": 10.3,
              "paymentInstrumentId": "19ceb7afa36ffe22fcd93c3518",
              "paymentMethodId": "BML"
          },
          {
              "amount": 10.4,
              "paymentCard": {
                  "cardType": "Visa",
                  "creditCardExpired": false
              },
              "paymentInstrumentId": "74c2fd8a9ede5712be8f18c638",
              "paymentMethodId": "CREDIT_CARD"
          }
      ],
      "productItems": [
          {
              "adjustedTax": 30,
              "basePrice": 199.99,
              "bonusProductLineItem": false,
              "gift": false,
              "itemId": "051e908cca031ebf8ee80cbb0a",
              "itemText": "Green Umbrella - Sustained Edition",
              "optionItems": [
                  {
                      "adjustedTax": 0,
                      "basePrice": 0,
                      "bonusProductLineItem": false,
                      "gift": false,
                      "itemId": "1b48e2474f18edefc34577daf8",
                      "itemText": "We will plant a tree for your order.",
                      "optionId": "plantATre",
                      "optionValueId": "000",
                      "price": 0,
                      "priceAfterItemDiscount": 0,
                      "priceAfterOrderDiscount": 0,
                      "productId": "000",
                      "productName": "Plant a tree.",
                      "quantity": 3,
                      "shipmentId": "me",
                      "tax": 0,
                      "taxBasis": 0,
                      "taxClassId": "standard",
                      "taxRate": 0.05
                  }
              ],
              "price": 599.97,
              "priceAfterItemDiscount": 599.97,
              "priceAfterOrderDiscount": 599.97,
              "productId": "green-umbrella",
              "productName": "Green Umbrella - Sustained Edition",
              "quantity": 3,
              "shipmentId": "me",
              "tax": 30,
              "taxBasis": 599.97,
              "taxClassId": "standard",
              "taxRate": 0.05
          },
          {
              "adjustedTax": 1.5,
              "basePrice": 29.99,
              "bonusProductLineItem": false,
              "gift": false,
              "itemId": "32f71ef20eccbc9b75d2114352",
              "itemText": "Green Bag",
              "price": 29.99,
              "priceAfterItemDiscount": 29.99,
              "priceAfterOrderDiscount": 29.99,
              "productId": "green-bag",
              "productName": "Green Bag",
              "quantity": 1,
              "shipmentId": "me",
              "tax": 1.5,
              "taxBasis": 29.99,
              "taxClassId": "standard",
              "taxRate": 0.05
          }
      ],
      "productSubTotal": 729.95,
      "productTotal": 729.95,
      "shipments": [
          {
              "adjustedMerchandizeTotalTax": 36.5,
              "adjustedShippingTotalTax": 0.8,
              "gift": false,
              "merchandizeTotalTax": 36.5,
              "productSubTotal": 729.95,
              "productTotal": 729.95,
              "shipmentId": "me",
              "shipmentTotal": 785.24,
              "shippingAddress": {
                  "address1": "4 Main St.X",
                  "address2": "Basement FlatX",
                  "city": "BostonX",
                  "companyName": "FlexoX",
                  "countryCode": "US",
                  "firstName": "JohnX",
                  "fullName": "JohnX H.X SmithX",
                  "id": "c27620f32e6e607c04a35fc2c7",
                  "jobTitle": "Bug FixerX",
                  "lastName": "SmithX",
                  "phone": "+1 33-33-33X",
                  "postalCode": "40982X",
                  "secondName": "H.X",
                  "stateCode": "MX",
                  "title": "MrX"
              },
              "shippingMethod": {
                  "description": "Order received within 7-10 business days",
                  "id": "001",
                  "name": "Ground",
                  "price": 15.99
              },
              "shippingStatus": "not_shipped",
              "shippingTotal": 15.99,
              "shippingTotalTax": 0.8,
              "taxTotal": 37.3
          }
      ],
      "shippingItems": [
          {
              "adjustedTax": 0.8,
              "basePrice": 15.99,
              "itemId": "bf466b517f08b5fae8d553b36c",
              "itemText": "Shipping",
              "price": 15.99,
              "priceAfterItemDiscount": 15.99,
              "shipmentId": "me",
              "tax": 0.8,
              "taxBasis": 15.99,
              "taxClassId": "standard",
              "taxRate": 0.05
          }
      ],
      "shippingTotal": 15.99,
      "shippingTotalTax": 0.8,
      "taxation": "net",
      "taxTotal": 37.3
  }
