#%RAML 1.0 NamedExample
value:
  {
    "amount": 1,
    "paymentCard":{
        "expirationYear":1990,
        "expirationMonth":7,
        "validFromMonth":8,
        "validFromYear":2007,
        "issueNumber":"i117",
        "maskedNumber":"*********1234",
        "holder":"Miller",
        "cardType":"Visa"
    },
    "paymentMethodId": "CREDIT_CARD"
  }
