#%RAML 1.0 NamedExample
value:
  {
      
      "discount" : 
          {
              "value" : 5,
              "type" : "percentage"
          },
      "itemText" : "MyOrderAdjustment",
      "level" : "order",
      "promotionId" : "manual adjustment"
      
  }