#%RAML 1.0 NamedExample
value:
  {
      "appliedDiscount" : 
        {
            "amount" : 15,
            "type" : "amount"
        },
      "itemText" : "AgentOrderAdjustment",
      "reasonCode" : "override manual promo"
   
  }