#%RAML 1.0 NamedExample
value:
  {
      "shipmentId": "me",
      "shipmentNo": "ignored shipment no",
      "shippingMethod": {
          "id": "003"
      },
      "shippingAddress": {
      "firstName": "Ward J",
      "lastName": "Adamek",
      "address1": "4911  Lincoln Street",
      "city": "IDANHA",
      "postalCode": "97350",
      "stateCode": "OR",
      "countryCode": "US"
      },
      "c_wapi-string": "shipment_custom_property"
  }
