#%RAML 1.0 NamedExample
value:
  {
      "firstName": "Ward J",
      "lastName": "Adamek",
      "address1": "4911  Lincoln Street",
      "city": "IDANHA",
      "postalCode": "97350",
      "stateCode": "OR",
      "countryCode": "US"
  }
