#%RAML 1.0 NamedExample
value:
  {
      "adjustedMerchandizeTotalTax": 30,
      "adjustedShippingTotalTax": 0.8,
      "agentBasket": false,
      "basketId": "a10ff320829cb0eef93ca5310a",
      "billingAddress": {
          "address1": "104 Presidential Way",
          "city": "Woburn",
          "countryCode": "US",
          "firstName": "Stephanie",
          "fullName": "Stephanie Miller",
          "id": "bfea663fd3de75d5be3ec02702",
          "lastName": "Miller",
          "postalCode": "01801",
          "stateCode": "MA"
      },
      "channelType": "storefront",
      "couponItems": [
          {
              "code": "5ties",
              "couponItemId": "cc6ef43f207bf64099288aec36",
              "statusCode": "no_applicable_promotion",
              "valid": true
          }
      ],
      "creationDate": "2019-10-17T08:29:55.340Z",
      "currency": "USD",
      "customerInfo": {
          "customerId": "beQeANXJNsd0xcINsB6cSrobQa",
          "email": "shopper@salesforce-test.com"
      },
      "lastModified": "2019-10-17T08:29:55.698Z",
      "merchandizeTotalTax": 30,
      "notes": {
      },
      "orderTotal": 646.76,
      "paymentInstruments": [
          {
              "amount": 0,
              "paymentCard": {
                  "cardType": "Visa",
                  "creditCardExpired": false
              },
              "paymentInstrumentId": "b7679bea661819b2de78b9de7d",
              "paymentMethodId": "CREDIT_CARD"
          }
      ],
      "productItems": [
          {
              "adjustedTax": 30,
              "basePrice": 199.99,
              "bonusProductLineItem": false,
              "gift": false,
              "itemId": "3d4e28425ce0b3a65b0ac4e163",
              "itemText": "Green Umbrella - Sustained Edition",
              "optionItems": [
                  {
                      "adjustedTax": 0,
                      "basePrice": 0,
                      "bonusProductLineItem": false,
                      "gift": false,
                      "itemId": "ff9452ed11fcf5c80f9143a8f1",
                      "itemText": "We will plant a tree for your order.",
                      "optionId": "plantATree",
                      "optionValueId": "000",
                      "price": 0,
                      "priceAfterItemDiscount": 0,
                      "priceAfterOrderDiscount": 0,
                      "productId": "000",
                      "productName": "Plant a tree.",
                      "quantity": 3,
                      "shipmentId": "me",
                      "tax": 0,
                      "taxBasis": 0,
                      "taxClassId": "standard",
                      "taxRate": 0.05
                  }
              ],
              "price": 599.97,
              "priceAfterItemDiscount": 599.97,
              "priceAfterOrderDiscount": 599.97,
              "productId": "green-umbrella",
              "productName": "Green Umbrella - Sustained Edition",
              "quantity": 3,
              "shipmentId": "me",
              "tax": 30,
              "taxBasis": 599.97,
              "taxClassId": "standard",
              "taxRate": 0.05
          }
      ],
      "productSubTotal": 599.97,
      "productTotal": 599.97,
      "shipments": [
          {
              "adjustedMerchandizeTotalTax": 30,
              "adjustedShippingTotalTax": 0.8,
              "gift": false,
              "merchandizeTotalTax": 30,
              "productSubTotal": 599.97,
              "productTotal": 599.97,
              "shipmentId": "me",
              "shipmentTotal": 646.76,
              "shippingAddress": {
                  "address1": "4911  Lincoln Street",
                  "city": "IDANHA",
                  "countryCode": "US",
                  "firstName": "Ward J",
                  "fullName": "Ward J Adamek",
                  "id": "b3e1269a2c1d0ad56694206741",
                  "lastName": "Adamek"
              },
              "shippingMethod": {
                  "description": "Order received in 2 business days",
                  "id": "002",
                  "name": "2-Day Express",
                  "price": 20.99
              },
              "shippingStatus": "not_shipped",
              "shippingTotal": 20.99,
              "shippingTotalTax": 1.05,
              "taxTotal": 36.05
          },
          {
              "adjustedMerchandizeTotalTax": 35,
              "adjustedShippingTotalTax": 0.8,
              "gift": false,
              "merchandizeTotalTax": 35,
              "productSubTotal": 599.97,
              "productTotal": 599.97,
              "shipmentId": "me2",
              "shipmentTotal": 646.76,
              "shippingAddress": {
                  "address1": "385  Prospect Valley Road",
                  "city": "Woburn",
                  "stateCode": "MA",
                  "countryCode": "US",
                  "firstName": "Stephanie",
                  "fullName": "Stephanie Miller",
                  "id": "84f06786daa68ae33af7e21ec6",
                  "lastName": "Miller"
              },
              "shippingMethod": {
                  "description": "Order received in 2 business days",
                  "id": "001",
                  "name": "2-Day Express",
                  "price": 15.99
              },
              "shippingStatus": "not_shipped",
              "shippingTotal": 15.99,
              "shippingTotalTax": 0.8,
              "taxTotal": 35
          }
      ],
      "shippingItems": [
          {
              "adjustedTax": 1.05,
              "basePrice": 20.99,
              "itemId": "d5ed0e58b8f8b5efe8d617a630",
              "itemText": "Shipping",
              "price": 20.99,
              "priceAfterItemDiscount": 20.99,
              "shipmentId": "me",
              "tax": 1.05,
              "taxBasis": 20.99,
              "taxClassId": "standard",
              "taxRate": 0.05
          },
          {
              "adjustedTax": 0.8,
              "basePrice": 15.99,
              "itemId": "6fea9966277c94e06b482a5c43",
              "itemText": "Shipping",
              "price": 15.99,
              "priceAfterItemDiscount": 15.99,
              "shipmentId": "me",
              "tax": 0.8,
              "taxBasis": 15.99,
              "taxClassId": "standard",
              "taxRate": 0.05
          }
      ],
      "shippingTotal": 36.98,
      "shippingTotalTax": 1.35,
      "taxation": "net",
      "taxTotal": 36.35
  }
