#%RAML 1.0 NamedExample
value:
  {
      "shipmentId": "me2",
      "shippingMethod": {
          "id": "001"
      },
      "shippingAddress": {
        "firstName": "Stephanie",
        "lastName": "Miller",
        "address1": "385  Prospect Valley Road",
        "city": "Woburn",
        "postalCode": "01801",
        "stateCode": "MA",
        "countryCode": "US"
      }
  }
