/*
 * Copyright (c) 2025, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
import CreatePageTool, { CreatePage } from './create-page-tool.js'
import * as fs from 'fs/promises'

// Mock fs/promises to avoid actual file operations
jest.mock('fs/promises', () => ({
    mkdir: jest.fn().mockResolvedValue(undefined),
    writeFile: jest.fn().mockResolvedValue(undefined),
    readFile: jest.fn().mockResolvedValue('const routes = []'),
}))

describe('CreatePage', () => {
    beforeEach(() => {
        jest.clearAllMocks()
    })

    it('should instantiate and set pageData', () => {
        const tool = new CreatePage()
        tool.pageData = {
            name: 'TestPage',
            route: '/test',
            location: '/tmp'
        }
        expect(tool.pageData.name).toBe('TestPage')
    })

    it('should call createPage without error', async () => {
        const tool = new CreatePage()
        tool.pageData = {
            name: 'TestPage',
            route: '/test',
            location: '/tmp'
        }
        await expect(tool.createPage()).resolves.toContain('Created')
    })

    it('should handle createPageFile error gracefully', async () => {
        fs.mkdir.mockRejectedValueOnce(new Error('mkdir error'))
        const tool = new CreatePage()
        tool.pageData = {
            name: 'TestPage',
            route: '/test',
            location: '/tmp'
        }
        await expect(tool.createPageFile('TestPage', '/tmp')).resolves.toContain('Error creating page file')
    })

    it('should handle addRouteToRoutesFile error gracefully', async () => {
        fs.readFile.mockRejectedValueOnce(new Error('read error'))
        const tool = new CreatePage()
        tool.pageData = {
            name: 'TestPage',
            route: '/test',
            location: '/tmp'
        }
        await expect(tool.addRouteToRoutesFile('TestPage', '/test')).resolves.toContain('Error updating routes file')
    })

    it('should reset currentStep and pageData to initial values', () => {
        const tool = new CreatePage()
        tool.currentStep = 5
        tool.pageData = {
            name: 'Something',
            route: '/some',
            location: '/some/path'
        }
        tool.reset()
        expect(tool.currentStep).toBe(0)
        expect(tool.pageData).toEqual({
            name: null,
            route: null,
            location: null
        })
    })

    it('should add route and import to routes file if not present', async () => {
        // Simulate a routes file with a routes array and a fallback
        fs.readFile.mockResolvedValueOnce(`const fallback = null\nconst routes = [\n]`)
        const tool = new CreatePage()
        tool.pageData = {
            name: 'TestPage',
            route: '/test',
            location: '/tmp'
        }
        await expect(tool.addRouteToRoutesFile('TestPage', '/test')).resolves.toContain('Added route')
        expect(fs.writeFile).toHaveBeenCalled()
    })

    it('should not add duplicate route if already present', async () => {
        fs.readFile.mockResolvedValueOnce(`const routes = [\n    { path: '/test', component: TestPage, exact: true }\n]`)
        const tool = new CreatePage()
        tool.pageData = {
            name: 'TestPage',
            route: '/test',
            location: '/tmp'
        }
        await expect(tool.addRouteToRoutesFile('TestPage', '/test')).resolves.toContain('Added route')
        // Should still call writeFile, but not add duplicate
        expect(fs.writeFile).toHaveBeenCalled()
    })

    it('should handle conversational create page flow', async () => {
        const mockServer = { sessionCounter: 1, sessions: {} }
        const args = { sessionId: undefined, answer: undefined }
        const result = await CreatePageTool.fn(args, mockServer)
        expect(result).toBeDefined()
        expect(result.content[0].text).toContain('sessionId')
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor 
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should advance to location step and suggest default dir if page route is provided', () => {
        const session = {answers: {}, step: 2}
        const answer = '/about'
        const sessionId = 'session-1'
        const serverInstance = {}
        process.env.PWA_STOREFRONT_APP_PATH = '/myapp'
        const result = CreatePage._handlePageRouteStep(session, answer, sessionId, serverInstance)
        const parsed = JSON.parse(result.content[0].text)
        expect(session.answers.pageRoute).toBe('/about')
        expect(session.step).toBe(3)
        expect(parsed.sessionId).toBe(sessionId)
        expect(parsed.instruction).toContain('/myapp/pages')
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor 
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should prompt for page route if not provided', () => {
        const session = {answers: {}, step: 2}
        const answer = ''
        const sessionId = 'session-2'
        const serverInstance = {}
        const result = CreatePage._handlePageRouteStep(session, answer, sessionId, serverInstance)
        const parsed = JSON.parse(result.content[0].text)
        expect(parsed.sessionId).toBe(sessionId)
        expect(parsed.instruction).toContain('page route')
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor 
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should use default dir if answer is yes in _handlePageLocationStep', async () => {
        const session = {answers: {pageName: 'Test', pageRoute: '/test'}, step: 3}
        const answer = 'yes'
        const sessionId = 'session-3'
        const serverInstance = {}
        process.env.PWA_STOREFRONT_APP_PATH = '/myapp'
        // Mock createPage to avoid file ops
        const createPageSpy = jest.spyOn(CreatePage.prototype, 'createPage').mockResolvedValue('created!')
        const result = await CreatePage._handlePageLocationStep(session, answer, sessionId, serverInstance)
        expect(session.answers.location).toBe('/myapp/pages')
        expect(session.step).toBe(99)
        const parsed = JSON.parse(result.content[0].text)
        expect(parsed.sessionId).toBe(sessionId)
        expect(parsed.message).toContain('created!')
        createPageSpy.mockRestore()
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor 
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should use custom dir if answer is not yes in _handlePageLocationStep', async () => {
        const session = {answers: {pageName: 'Test', pageRoute: '/test'}, step: 3}
        const answer = '/custom/pages'
        const sessionId = 'session-4'
        const serverInstance = {}
        // Mock createPage to avoid file ops
        const createPageSpy = jest.spyOn(CreatePage.prototype, 'createPage').mockResolvedValue('created!')
        const result = await CreatePage._handlePageLocationStep(session, answer, sessionId, serverInstance)
        expect(session.answers.location).toBe('/custom/pages')
        expect(session.step).toBe(99)
        const parsed = JSON.parse(result.content[0].text)
        expect(parsed.sessionId).toBe(sessionId)
        expect(parsed.message).toContain('created!')
        createPageSpy.mockRestore()
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor 
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should prompt again for location if answer is empty in _handlePageLocationStep', async () => {
        const session = {answers: {pageName: 'Test', pageRoute: '/test'}, step: 3}
        const answer = ''
        const sessionId = 'session-5'
        const serverInstance = {}
        process.env.PWA_STOREFRONT_APP_PATH = '/myapp'
        const result = await CreatePage._handlePageLocationStep(session, answer, sessionId, serverInstance)
        const parsed = JSON.parse(result.content[0].text)
        expect(parsed.sessionId).toBe(sessionId)
        expect(parsed.instruction).toContain('/myapp/pages')
    })

    it('should prefix import path with ./ if not already relative', async () => {
        // Simulate a routes file with a routes array and no imports
        fs.readFile.mockResolvedValueOnce('const routes = [\n]')
        const tool = new CreatePage()
        // Set up so that the relative path will not start with '.'
        // routesFile: /a/b/routes.jsx, pageDir: /a/c/page
        // relativeImportPath: ../c/page (should become ./../c/page)
        tool.pageData = {
            name: 'TestPage',
            route: '/test',
            location: '/a/c'
        }
        // Patch path.resolve and path.relative for this test
        const originalResolve = jest.requireActual('path').resolve
        const originalRelative = jest.requireActual('path').relative
        jest.spyOn(require('path'), 'resolve').mockImplementation((...args) => '/a/b/routes.jsx')
        jest.spyOn(require('path'), 'relative').mockImplementation((from, to) => '../c/test-page')
        await tool.addRouteToRoutesFile('TestPage', '/test')
        // Check that writeFile was called with an import path starting with './'
        const written = fs.writeFile.mock.calls[0][1]
        expect(written).toContain("import('../c/test-page')")
        // Restore
        require('path').resolve.mockRestore()
        require('path').relative.mockRestore()
    })

    it('should insert new route before ..._routes in routes array', async () => {
        const routesWithSpread = `const routes = [\n    ..._routes\n]`
        fs.readFile.mockResolvedValueOnce(routesWithSpread)
        const tool = new CreatePage()
        tool.pageData = {
            name: 'TestPage',
            route: '/test',
            location: '/tmp'
        }
        await tool.addRouteToRoutesFile('TestPage', '/test')
        // The new route should appear before ..._routes
        const written = fs.writeFile.mock.calls[0][1]
        const idxRoute = written.indexOf("path: '/test'")
        const idxSpread = written.indexOf('..._routes')
        expect(idxRoute).toBeGreaterThan(-1)
        expect(idxSpread).toBeGreaterThan(-1)
        expect(idxRoute).toBeLessThan(idxSpread)
    })

    it('should add a comma to the last route if missing before inserting new route (no ..._routes)', async () => {
        // Simulate a routes file with multiple routes, last one without a trailing comma
        const originalRoutes = `const routes = [
    {
        path: '/',
        component: Home,
        exact: true
    },
    {
        path: '/about',
        component: AboutUs,
        exact: true
    },
    {
        path: '/test',
        component: Test,
        exact: true
    }
]`
        fs.readFile.mockResolvedValueOnce(originalRoutes)
        const tool = new CreatePage()
        tool.pageData = {
            name: 'Book',
            route: '/book',
            location: '/tmp'
        }
        await tool.addRouteToRoutesFile('Book', '/book')
        const written = fs.writeFile.mock.calls[0][1]
        // Check that the last original route now ends with a comma
        expect(written).toMatch(/component: Test,\s*exact: true\s*},\s*{\s*path: '\/book'/s)
        // Check that the new route is present
        expect(written).toContain("path: '/book'")
        expect(written).toContain('component: Book')
        // The final array should end with ]
        expect(written.trim().endsWith(']')).toBe(true)
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor 
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should advance to route step and prompt for page route if page name is provided', () => {
        const session = {answers: {}, step: 1}
        const answer = 'AboutPage'
        const sessionId = 'session-6'
        const serverInstance = {}
        const result = CreatePage._handlePageNameStep(session, answer, sessionId, serverInstance)
        const parsed = JSON.parse(result.content[0].text)
        expect(session.answers.pageName).toBe('AboutPage')
        expect(session.step).toBe(2)
        expect(parsed.sessionId).toBe(sessionId)
        expect(parsed.instruction).toContain('page route')
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor 
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should prompt for page name if not provided', () => {
        const session = {answers: {}, step: 1}
        const answer = ''
        const sessionId = 'session-7'
        const serverInstance = {}
        const result = CreatePage._handlePageNameStep(session, answer, sessionId, serverInstance)
        const parsed = JSON.parse(result.content[0].text)
        expect(parsed.sessionId).toBe(sessionId)
        expect(parsed.instruction).toContain('page name')
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should call the correct step handler in handleConversationalCreatePage for step 1, 2, 3, and default', async () => {
        const mockServer = {sessionCounter: 1, sessions: {}}
        // Step 1
        mockServer.sessions['s1'] = {step: 1, answers: {}}
        let result = await CreatePage.handleConversationalCreatePage({sessionId: 's1', answer: 'PageName'}, mockServer)
        expect(JSON.parse(result.content[0].text).instruction).toContain('page route')
        // Step 2
        mockServer.sessions['s2'] = {step: 2, answers: {}}
        result = await CreatePage.handleConversationalCreatePage({sessionId: 's2', answer: '/route'}, mockServer)
        expect(JSON.parse(result.content[0].text).instruction).toContain('pages directory')
        // Step 3
        mockServer.sessions['s3'] = {step: 3, answers: {pageName: 'Test', pageRoute: '/test'}}
        jest.spyOn(CreatePage.prototype, 'createPage').mockResolvedValue('created!')
        result = await CreatePage.handleConversationalCreatePage({sessionId: 's3', answer: 'yes'}, mockServer)
        expect(JSON.parse(result.content[0].text).message).toContain('created!')
        CreatePage.prototype.createPage.mockRestore()
        // Default
        mockServer.sessions['s4'] = {step: 99, answers: {}}
        result = await CreatePage.handleConversationalCreatePage({sessionId: 's4'}, mockServer)
        expect(JSON.parse(result.content[0].text).message).toContain('Page creation flow complete.')
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should return _next with directory prompt if answer is falsy in _handlePageLocationStep', async () => {
        const session = {answers: {pageName: 'Test', pageRoute: '/test'}, step: 3}
        const answer = ''
        const sessionId = 'session-8'
        const serverInstance = {}
        process.env.PWA_STOREFRONT_APP_PATH = '/myapp'
        const result = await CreatePage._handlePageLocationStep(session, answer, sessionId, serverInstance)
        const parsed = JSON.parse(result.content[0].text)
        expect(parsed.sessionId).toBe(sessionId)
        expect(parsed.instruction).toContain('/myapp/pages')
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should return success message from createPageFile', async () => {
        const tool = new CreatePage()
        jest.spyOn(fs, 'mkdir').mockResolvedValue(undefined)
        jest.spyOn(fs, 'writeFile').mockResolvedValue(undefined)
        const msg = await tool.createPageFile('Book', '/tmp')
        expect(msg).toContain('Created')
        fs.mkdir.mockRestore()
        fs.writeFile.mockRestore()
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should return success message from addRouteToRoutesFile', async () => {
        const tool = new CreatePage()
        tool.pageData = {name: 'Book', route: '/book', location: '/tmp'}
        jest.spyOn(fs, 'readFile').mockResolvedValue('const routes = []')
        jest.spyOn(fs, 'writeFile').mockResolvedValue(undefined)
        const msg = await tool.addRouteToRoutesFile('Book', '/book')
        expect(msg).toContain('Added route')
        fs.readFile.mockRestore()
        fs.writeFile.mockRestore()
    })

    /*
     * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor
     * This test was generated with the following model: Claude 3.5 Sonnet
     */
    it('should return error message from addRouteToRoutesFile on error', async () => {
        const tool = new CreatePage()
        tool.pageData = {name: 'Book', route: '/book', location: '/tmp'}
        jest.spyOn(fs, 'readFile').mockRejectedValue(new Error('fail!'))
        const msg = await tool.addRouteToRoutesFile('Book', '/book')
        expect(msg).toContain('Error updating routes file')
        fs.readFile.mockRestore()
    })
}) 