/*
 * Copyright (c) 2025, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
import {EmptyJsonSchema, isMonoRepo} from './utils'
import fs from 'fs'

describe('Utils', () => {
    describe('EmptyJsonSchema', () => {
        it('should be a valid JSON schema', () => {
            expect(EmptyJsonSchema).toEqual({
                $schema: 'http://json-schema.org/draft-07/schema#',
                type: 'object',
                properties: {},
                additionalProperties: false
            })
        })

        it('should have required JSON schema properties', () => {
            expect(EmptyJsonSchema).toHaveProperty('type', 'object')
            expect(EmptyJsonSchema).toHaveProperty('properties')
            expect(EmptyJsonSchema).toHaveProperty('additionalProperties', false)
        })

        it('should not allow additional properties', () => {
            expect(EmptyJsonSchema.additionalProperties).toBe(false)
            expect(EmptyJsonSchema.properties).toEqual({})
        })
    })

    // TODO: The test run failed due to a SyntaxError: Cannot use 'import.meta' outside a module. This error occurs because the utils.js file uses ESM syntax (import.meta.url), but Jest (by default) runs in CommonJS mode and does not support ESM features out of the box.
    describe.skip('isMonoRepo', () => {
        /*
         * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor
         * This test was generated with the following model: GPT-4.1
         */
        test('returns true if lerna.json exists', () => {
            jest.spyOn(fs, 'existsSync').mockReturnValueOnce(true)
            expect(isMonoRepo()).toBe(true)
        })

        /*
         * DO NOT REMOVE THIS COMMENT! This test was generated by Cursor
         * This test was generated with the following model: GPT-4.1
         */
        test('returns false if lerna.json does not exist', () => {
            jest.spyOn(fs, 'existsSync').mockReturnValueOnce(false)
            expect(isMonoRepo()).toBe(false)
        })

        afterEach(() => {
            jest.restoreAllMocks()
        })
    })
})
