name: e2e_generate_app
inputs:
  PROJECT_KEY:
    description: Project key to specify project to generate ("retail-app-demo", "retail-app-ext" or "retail-app-no-ext")
    required: true
    type: string

  TEMPLATE_VERSION:
    description: Version of the template to use for the project
    required: false
    type: string

outputs:
  project_path:
    description: Path to the generated project directory
    value: ${{ steps.generate_project.outputs.project_path }}

runs:
  using: composite
  steps:
  - name: Generate new project based on project-key
    id: generate_project
    run: |
      COMMAND="node e2e/scripts/generate-project.js --project-key ${{ inputs.PROJECT_KEY }}"
      if [[ -n "${{ inputs.TEMPLATE_VERSION }}" ]]; then
        COMMAND="$COMMAND --templateVersion ${{ inputs.TEMPLATE_VERSION }}"
      fi
      $COMMAND

      # Return path to the generated project
      GENERATED_PROJECTS_DIR=$(node -e "console.log(require('./e2e/config.js').GENERATED_PROJECTS_DIR)")
      echo "project_path=$GENERATED_PROJECTS_DIR/${{ inputs.PROJECT_KEY }}" >> $GITHUB_OUTPUT
    shell: bash
