/** @jsx jsx */
import {jsx} from 'theme-ui'
import PropTypes from 'prop-types'
import Markdown from 'markdown-to-jsx'
import theme from '../gatsby-plugin-theme-ui/'
import TableWrapper from './TableWrapper'
/**
 * Table for React props generated by react-docgen
 *
 * @see https://github.com/episodeyang/react-component-props-table/
 */
const PropsTable = (props) => {
    let {className = '', propMetaData = [], ..._props} = props
    if (className) className += ' component-props-table'
    return (
        <TableWrapper>
            <table className={className} {..._props} sx={theme.styles.table}>
                <thead>
                    <tr>
                        <th>Name &amp; Description</th>
                        <th>Type</th>
                        <th>Default</th>
                    </tr>
                </thead>
                <tbody>
                    {Object.keys(propMetaData).map((key) => {
                        const prop = propMetaData[key]
                        return (
                            <tr key={key}>
                                <td>
                                    <span sx={theme.styles.inlineCode}>{prop.name}</span>

                                    {prop.required && (
                                        <small sx={{marginLeft: 'sm', color: 'alert'}}>
                                            required
                                        </small>
                                    )}

                                    {prop.docblock ? (
                                        <div className="docblock" sx={{marginTop: 'xs'}}>
                                            <Markdown>{prop.docblock}</Markdown>
                                        </div>
                                    ) : (
                                        <div />
                                    )}
                                </td>
                                <td>{prop.parentType ? prop.parentType.name : ''}</td>
                                {prop.defaultValue ? (
                                    <td>{prop.defaultValue.value}</td>
                                ) : (
                                    <td sx={{color: 'mediumGray'}}>none</td>
                                )}
                            </tr>
                        )
                    })}
                </tbody>
            </table>
        </TableWrapper>
    )
}

PropsTable.propTypes = {
    /** this is the `metadata.props` field of what metadata you get from the react-docgen-loader.  */
    propMetaData: PropTypes.array
}
PropsTable.defaultProps = {
    propMetaData: []
}

export default PropsTable
