name: push_to_mrt
inputs:
  CWD:
    description: Project directory
    default: ${{ github.workspace }}
  TARGET:
    description: MRT target
  FLAGS:
    description: Push flags
runs:
  using: composite
  steps:
    - name: Push Bundle to MRT
      run: |-
        cd ${{ inputs.CWD }}
        project="alex-test"
        build="build ${{ github.run_id }} on ${{ github.ref }} (${{ github.sha }})"
        if [[ ${{ inputs.TARGET }} ]]; then
          npm run build
        fi
      shell: bash
