#%RAML 1.0 Trait

usage: |
  To be applied to endpoints that support etag based conditional requests etags as 
  described in [conditional requests](https://confluence.internal.salesforce.com/display/ENG/RESTful+APIs+Conventions+and+Standards+v1.1).
  Parameters:
    - `responseStatus` (integer): |
      The status this endpoint will return. Iif there are multiple statutes with this purpose 
      in the endpoint, this trait won't be a good option.

headers: 
  If-None-Match:
    description: ETag that is required in the cache
    required: false
    examples:
      UUID-etag: 155f0df6-8dfc-11e7-bb31-be2e44b06b34

responses: 
  <<responseStatus>>:
    headers: 
      ETag:
        description: The current value of the entity tag for the requested variant
        examples:
          UUID-etag: 155f0df6-8dfc-11e7-bb31-be2e44b06b34


