name: datadog
inputs:
  datadog_api_key:
    description: "Datadog API key"
  TOTAL_PACKAGES:
    description: "Total # of packages"
runs:
  using: composite
  steps:
    - name: Send metrics to Datadog
      run : |
        # For the datadog cli, it must be installed via python
        # to install python packages on CI environment, we must activate the virtual env
        # or otherwise it throws error: externally-managed-environment
        python3 -m venv venv
        source venv/bin/activate
        pip install datadog

        # Add a dogrc so we can submit metrics to datadog
        printf "[Connection]\napikey = ${{inputs.datadog_api_key}}\nappkey =\n" > ~/.dogrc

        dog metric post mobify_platform_sdks.generated_project_total_packages ${{ inputs.TOTAL_PACKAGES }}
      shell: bash
