#%RAML 1.0 NamedExample
# This example is for shopper context request/response
value:
  {
    "effectiveDateTime": null,
    "customQualifiers" : 
    {
      "deviceType": "iPad",
      "authenticated": null,
      "operatingSystem": "iOS",
      "storeId": "SLC1",
    }
  }