#%RAML 1.0 NamedExample
# This example is for shopper context request/response
value:
  {
    "customQualifiers" : 
    {
      "deviceType": "iPad",
      "sourceCodeGroup": "Sale",
      "referrerURL": "https://wwww.google.com",
      "currency": "USD",
      "referrerHost": "google",
      "ipAddress": "189.0.0.10",
      "zipCode": "11111",
      "country": "US",
      "region": "West",
      "city": "SLC",
      "operatingSystem": "iOS",
      "customergroupId": "",
      "storeId": "SLC1"
    }
  }