#%RAML 1.0 NamedExample
value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/shopper-context-no-found",
    "detail": "Shopper Context for ORGANIZATION_ID: f_ecom_bhbv_prd and USID: 7e1f65fb-185c-4788-8cec-05fef8dac77d not found in Repository.",
    "title": "Shopper Context Not Found"
  }