#%RAML 1.0 NamedExample
value:
   {
     "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unauthorized",
     "title": "Unauthorized",
     "detail": "Your shopper JWT is invalid and could not be used to identify the API client."
   }