#%RAML 1.0 NamedExample
value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/forbidden",
    "title": "Forbidden",
    "detail": "Your shopper JWT is valid, but you have no permissions to access the resource."
  }