#%RAML 1.0 NamedExample
value:
  {
    "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/usid-not-matching-with-token",
    "detail": "Usid in incoming request does not match Usid in token.",
    "title": "Usid not matching with token"
  }