#%RAML 1.0 Trait

usage: |
  To be applied to define the **response** on endpoints that use etags as 
  described in [conditional requests](https://confluence.internal.salesforce.com/display/ENG/RESTful+APIs+Conventions+and+Standards+v1.1).
  To describe the request part consider using `etag-conditional-request.raml`, the reason
  this is not described in that trait is because this could be used separatelly in endpoints
  that do not accept an etag-conditional-request but yet will return an etag, for instance: 
  a synchronous PUT.
  Parameters:
    - `responseStatus` (integer): |
      The status this endpoint will return. Iif there are multiple statutes with this purpose 
      in the endpoint, this trait won't be a good option.

responses: 
  <<responseStatus>>:
    headers: 
      ETag:
        description: The current value of the entity tag for the requested variant
        examples:
          UUID-etag: 155f0df6-8dfc-11e7-bb31-be2e44b06b34

