  description: The user has sent too many requests in a given amount of time, and rate limiting is in effect.
  headers: 
    X-RateLimit-1M-Limit:
      description: The 1 minute maximum number of requests permitted per hour. 
    X-RateLimit-1M-Remaining:     
      description: The 1 minute number of requests remaining in the current rate limit window.
    X-RateLimit-1M-Reset:
      description: The 1 minute time at which the current rate limit window resets in UTC epoch seconds.
    X-RateLimit-5M-Limit:
      description: The 5 minute maximum number of requests permitted per hour.  
    X-RateLimit-5M-Remaining:     
      description: The 5 minute number of requests remaining in the current rate limit window.
    X-RateLimit-5M-Reset:
      description: The 5 minute time at which the current rate limit window resets in UTC epoch seconds.