#%RAML 1.0 NamedExample
value:
  {
    "amount": 100,
    "balance": 100,
    "enabled": true,
    "maskedGiftCertificateCode": "************FJWQ",
    "merchantId": "00000001",
    "recipientEmail": "p@gmail.com",
    "recipientName": "sampleuser",
    "senderName": "Salesforce Support",
    "status": "issued"
  }