/*
 * Copyright (c) 2024, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
/* istanbul ignore file */

// Hey! This file is a magic placeholder.
// Do not edit this file.

// During build process, this file is replaced with the actual implementation.
// see pwa-kit-extension-sdk/configs/utils.ts for more details.
export const getApplicationExtensions = () => {
    console.error('Something went wrong. Cannot load application extensions.')
    return []
}
