name: setup_windows
inputs:
  cwd:
    required: false
    default: "${PWD}"
  node:
    required: true
  npm:
    required: false
  update_npm:
    required: false
    default: false
description: "Setup Windows Machine"
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: npm

    - name: Update NPM version
      if: inputs.update_npm
      run: |-
        npm install -g npm@${{ inputs.npm }}
      shell: bash

    - name: Install Dependencies
      run: |-
        # Install node dependencies
        npm ci
      shell: bash
