name: 'Changelog Check'
description: 'Check if changelog is updated for the changed packages'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch full history to access all commits

    - name: Fetch PR labels
      id: fetch_labels
      run: |
        PR_LABELS=$(curl -s -H "Authorization: token ${{ inputs.github_token }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.pr_number }}/labels" | \
          jq -r '.[].name')
        echo "PR_LABELS=${PR_LABELS}" >> $GITHUB_ENV
      shell: bash

    - name: Debugging Info
      run: |
        echo "Event before: ${{ github.event.before }}"
        echo "Current SHA: ${{ github.sha }}"
        echo "PR labels: $PR_LABELS"
      shell: bash

    - name: Check if changelog is updated
      run: |
        if [ -z "${{ github.event.before }}" ] || [ -z "${{ github.sha }}" ]; then
          echo "Error: SHA values are missing or invalid."
          exit 1
        fi

        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "Changed files: $CHANGED_FILES"
        
        PACKAGES=("commerce-sdk-react" "pwa-kit-dev" "template-express-minimal" "template-typescript-minimal" "internal-lib-build" "pwa-kit-react-sdk" "template-mrt-reference-app" "test-commerce-sdk-react" "pwa-kit-create-app" "pwa-kit-runtime" "template-retail-react-app")
        SKIP_CHANGELOG_LABEL="skip changelog"

        for PACKAGE in "${PACKAGES[@]}"; do
          if echo "$CHANGED_FILES" | grep -q "^packages/$PACKAGE/"; then
            if ! echo "$CHANGED_FILES" | grep -q "^packages/$PACKAGE/changelog.md"; then
              if ! echo "$PR_LABELS" | grep -q "$SKIP_CHANGELOG_LABEL"; then
                echo "Changelog.md was not updated for package $PACKAGE. Please update the changelog or add 'skip changelog' label to the pull request."
                exit 1
              fi
            fi
          fi
        done
      shell: bash
