#%RAML 1.0 NamedExample
# This example is for shopper context request/response
value:
  {
    "effectiveDateTime": "2020-12-20T00:00:00Z",
    "customQualifiers" : 
    {
      "deviceType": "mobile",
      "sourceCodeGroup": "Sale",
      "referrerURL": "https://www.google.com",
      "currency": "USD",
      "referrerHost": "google",
      "authenticated": "no",
      "ipAddress": "189.0.0.0",
      "zipCode": "11111",
      "country": "US",
      "region": "West",
      "city": "SLC",
      "operatingSystem": "Android",
      "customergroupId": ""
    }
  }