#%RAML 1.0 Library
annotationTypes:
    types:
      allowedTargets: [TypeDeclaration,API]
      properties:
        className?:
          type: string
        implementationClassName?:
          type: string
        usePrimitiveType?:
          type: boolean
        abstract?:
          type: boolean
        plugins?: any[]
    resources:
        allowedTargets: [Resource, Method, Response, API]
        properties:
            plugins?: any[]
    methods:
        allowedTargets: [Method, API]
        properties:
            plugins?: any[]

    responseClasses:
        allowedTargets: [Method, API]
        properties:
            plugins?: any[]

    responses:
        allowedTargets: [Response, API]
        properties:
            plugins?: any[]
