name: lighthouse_ci
runs:
  using: composite
  steps:
  - name: Run Lighthouse CI on the PWA
    # This test is flaky, so let's try it three times!
    run: npm run test:lighthouse --prefix packages/template-retail-react-app || npm run test:lighthouse --prefix packages/template-retail-react-app || npm run test:lighthouse --prefix packages/template-retail-react-app
    shell: bash
