#%RAML 1.0 SecurityScheme

description: |
  Salesforce Cloud-to-Cloud Authentication.
type: x-custom
displayName: GDoT

describedBy:
  headers:
    Authorization:
      description: |
        Cloud-to-Cloud token
      type: string
      pattern: "C2C .*"
      examples: 
        Example: C2C b325e95c-2cd7-11e5-b345-feff819cdc9f
  responses:
    401:
      description: Unauthorized. Your token is invalid or expired and could not be used to identify a cloud, service, tenant or tenant-group.
      body:
        application/json:
          type: !include ../dataTypes/error-response.raml
          example:
            type: "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unauthorized"
            title: Unauthorized
            detail: Your token is invalid or expired and could not be used to identify a cloud, service, tenant or tenant-group.

    403:
      description: Forbidden. Your token is valid, but you have no permissions to access the resource.
      body:
        application/json:
          type: !include ../dataTypes/error-response.raml
          example:
            type: "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/forbidden"
            title: Forbidden
            detail: Your token is valid, but you have no permissions to access the resource.