/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2021 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
const routes = [
    /^\/\/?$/,
    /^\/letmein\/?$/,
    /^\/fr\/?$/,
    /^\/en\/?$/,
    /^\/.*?\/email-signup\/?$/,
    /^\/.*?page-not-found\/?$/,
    /^\/.*?cms-demo\/?$/,
    /^\/.*?\/content\/.*?\/?$/,
    /^\/.*?\/checkout.*?\/?$/,
    /^\/.*?cartes-cadeaux.*?\/?$/,
    /^\/.*?Gift-Cards\/?$/,
    /^\/.*?gift-card-activation\/?$/,
    /^\/.*?activation-carte-cadeau\/?$/,
    /^\/.*?gift-card-balance\/?$/,
    /^\/.*?GiftCard-ShowPhysical\/?$/,
    /^\/.*?GiftCard-ShowEGift\/?$/,
    /^\/.*?cart.*?\/?$/,
    /^\/.*?\/faq.*?\/?$/,
    /^\/.*?\/cart.*?\/?$/,
    /^\/.*?confirmation\/?$/,
    /^\/style-guide\/?$/,
    /^\/.*?\/story\/.*?\/?$/,
    /^\/.*?Account-Login\/?$/,
    /^\/.*?Unsubscribe-Start\/?$/,
    /^\/.*?Account-Create\/?$/,
    /^\/.*?Stores-Detail.*?\/?$/,
    /^\/.*?Account-Show.*?\/?$/,
    /^\/.*?Account-EditProfile.*?\/?$/,
    /^\/.*?Address-List.*?\/?$/,
    /^\/.*?PaymentInstruments-List.*?\/?$/,
    /^\/.*?Order-History.*?\/?$/,
    /^\/.*?order-status.*?\/?$/,
    /^\/.*?Wishlist-Show.*?\/?$/,
    /^\/.*?Account-ChangeEmail.*?\/?$/,
    /^\/.*?Account-ChangePassword.*?\/?$/,
    /^\/.*?Preferred-Store.*?\/?$/,
    /^\/.*?reset-password.*?\/?$/,
    /^\/.*?Account-SetNewPassword.*?\/?$/,
    /^\/.*?store-locator.*?\/?$/,
    /^\/.*?Garment-Care\/?$/,
    /^\/.*?Extended-Sizes\/?$/,
    /^\/.*?Conciergerie\/?$/,
    /^\/.*?\/global-elements\/?$/,
    /^\/.*?WriteReviewPage\/?$/,
    /^\/.*?Sitemap\/?$/,
    /^\/.*?Contact-Us\/?$/,
    /^\/.*?CASL\/?$/,
    /^\/products\/[^/]+\/?$/,
    /^\/.*?\/[^/]+\.html\/?$/,
    /^\/[^/]+\/.*?\/?$/,
    /^\/.*?\/?$/
]
export default routes
