#%RAML 1.0 Library
usage: |-
  Data Types that don't fit into any specific category like error responses or search related types can be entered into this catch-all library.
types:
  NoPropertiesAllowed:
    type: object
    additionalProperties: false
    description: |-
      This type is intended as an abstract super type that indicates that no additional properties are supported for this type and its sub types. All types that do not support any additional properties should inherit from this type. This type is not allowed to be used directly in any API and should always be extended.
  SpecifiedPropertiesAllowed:
    type: object
    description: |-
      This type is intended as an abstract super type that indicates that additional properties are supported for this type and its sub types (unless one of those subtypes inherits from `ClosedObject`). All types that support any additional properties should inherit from this type. This type is not allowed to be used directly in any API and should always be extended.

      To indicate that the properties were defined and expected to be handled as additional properties, they are expected to be prefixed with a `c_`. The type will reject any property that does not fit this pattern, only allowing additional properties beginning with the known prefix.
    additionalProperties: true
    properties:
      /^c_.+$/?:
        displayName: Additional Property Support
        description:  |-
          This type supports additional properties passed along with the defined properties of this API. To indicate that the properties were defined and expected to be handled as additional properties, they are expected to be prefixed with a `c_`. The type will reject any property that does not fit this pattern, only allowing additional properties beginning with the known prefix.
        example:
          c_faxNumber
        type: any