#%RAML 1.0 NamedExample
value:
  {
    "limit" : 1,
    "data" : 
    [
        {
          "address1" : "10 Free Way",
          "addressId" : "private",
          "city" : "Woburn",
          "countryCode" : "US",
          "firstName" : "James",
          "fullName" : "James Last",
          "lastName" : "Last",
          "postalCode" : "01827",
          "salutation" : "Mr.",
          "stateCode" : "MA"
        }
    ],
    "offset" : 0,
    "total" : 2
  }
