#%RAML 1.0 NamedExample
value:
  {
    "addressId": "home_address",
    "address1" : "5 Wall St",
    "address2" : "24 Presidential Way",
    "city" : "Burlington",
    "companyName" : "Salesforce Commerce Cloud",
    "countryCode" : "US",
    "creationDate": "2020-02-14T21:13:29.769Z",
    "firstName": "John",
    "fullName": "John Jim Murphy",
    "jobTitle" : "Developer",
    "lastModified": "2020-02-14T21:13:29.770Z",
    "lastName" : "Murphy",
    "phone" : "408-555-1212",
    "postalCode" : "01805",
    "postBox" : "12a",
    "preferred" : false,
    "salutation" : "Mr.",
    "secondName" : "Jim",
    "stateCode": "MA",
    "title": "Dr."
  }