#%RAML 1.0 NamedExample
value:
  {
    "paymentCard": {
                    "expirationYear":2027,
                    "expirationMonth":7,
                    "validFromMonth":8,
                    "validFromYear":2007,
                    "issueNumber":"i117",
                    "number":"1234567",
                    "holder":"John Smith",
                    "cardType":"MasterCard"
                    },
    "giftCertificateCode": "gift_code7",
    "paymentMethodId": "OCAPI_Payment_Simple",
    "bankRoutingNumber":"bankrouting3776"
  }