#%RAML 1.0 NamedExample
value:
  {
    "bankRoutingNumber" : "bankrouting3776",
    "giftCertificateCodeMasked" : "******ode7",
    "paymentBankAccount" : 
    {
    },
    "paymentCard" : 
    {
        "cardType" : "MasterCard",
        "creditCardExpired" : false,
        "expirationMonth" : 7,
        "expirationYear" : 2027,
        "holder" : "John Smith",
        "issueNumber" : "i117",
        "maskedNumber" : "***4567",
        "numberLastDigits" : "4567",
        "validFromMonth" : 8,
        "validFromYear" : 2007
    },
    "paymentMethodId" : "OCAPI_Payment_Simple",
    "paymentInstrumentId" : "cdOLciWbOsYl6aaadkwcsx9xHH"
  }