#%RAML 1.0 NamedExample
value:
  {
    "authType": "registered",
    "creationDate": "2020-02-13T17:44:15.892Z",
    "customerId": "abkd9LhOWzAiAFubdEDChtkMHW",
    "customerNo": "00006002",
    "email": "jsmith@test.com",
    "enabled": true,
    "firstName": "John",
    "lastModified": "2020-02-13T17:44:15.898Z",
    "lastName": "Smith",
    "login": "jsmith"
}