#%RAML 1.0 NamedExample
value:
  {
    "adresses": [
        {
            "address1": "10 Presidential Way",
            "addressId": "me",
            "city": "Woburn",
            "countryCode": "US",
            "firstName": "John",
            "fullName": "John M. Smith",
            "lastName": "Smith",
            "postalCode": "01827",
            "salutation": "Mr.",
            "stateCode": "MA"
        }
    ],
    "authType": "registered",
    "creationDate": "2020-02-14T20:39:53.818Z",
    "customerId": "abfTEMDZOgi3JPrkHjv9IhoziM",
    "customerNo": "00010009",
    "email": "jsmith@demandware.com",
    "firstName": "John",
    "gender": 1,
    "lastName": "Smith",
    "paymentInstruments": [
        {
            "bankRoutingNumber": "0763564",
            "creationDate": "2017-08-20T11:30:36.000Z",
            "lastModified": "2017-08-20T11:30:50.000Z",
            "maskedGiftCertificateCode": "***********ode",
            "paymentBankAccount": {
                "driversLicenseStateCode": "CO",
                "driversLicenseLastDigits": "9742",
                "holder": "John Doe",
                "maskedDriversLicense": "**********2159",
                "maskedNumber": "*************1234",
                "numberLastDigits": "8700"
            },
            "paymentCard": {
                "cardType": "Visa",
                "creditCardExpired": false,
                "expirationMonth": 2,
                "expirationYear": 2022,
                "holder": "John Smith",
                "maskedNumber": "***********ber2",
                "numberLastDigits": "ber2"
            },
            "paymentInstrumentId": "beybQiWcyatEEaaadniwhKxxFl",
            "paymentMethodId": "CREDIT_CARD",
            "uuid": "beybQiWcyatEEaaadniwhKxxFl"
        }
    ],
    "phoneBusiness": "234560003",
    "phoneHome": "123450003",
    "phoneMobile": "345670003"
  }