#%RAML 1.0 NamedExample
value:
  {
   "limit" : 1,
   "data" : 
   [
      {
          "coRegistrant": {
             "email": "janedoe@example.com",
             "firstName": "Jane",
             "lastName": "Doe",
             "role": "Bride"
          },
         "creationDate": "2019-10-18T22:06:28.965Z",
         "currentShippingAddressInfo": {
            "addressId": "home_address",
            "title": "home_address, John Murphy, Burlington"
         },
         "customerProductListItems" : 
         [
            
            {
                "description" : "Description",
                "id": "30f35c187ea255ccb633c3ba11",
                "priority": 4,
                "productId": "SimpleProduct",
                "public": false,
                "purchasedQuantity": 0,
                "quantity": 2,
                "type": "product"
            }
         ],
         "postEventShippingAddressInfo": {
            "addressId": "home_address",
            "title": "home_address, John Murphy, Burlington"
          },
          "productListShippingAddress": {
            "addressId": "home_address",
            "city": "Burlington",
            "firstName": "John",
            "lastName": "Murphy"
          },
         "name": "OurProductList",
          "registrant": {
            "email": "johndoe@example.com",
            "firstName": "John",
            "lastName": "Doe",
            "role": "Groom"
         },
         "lastModified": "2019-10-18T22:06:28.971Z",
         "description" : "a productlist",
         "event" : 
         {
           "city" : "any city",
           "country" : "USA",
           "type": "product_list_event"
         },
         "shippingAddressLink": {
            "addressId": "home_address",
            "title": "home_address, John Murphy, Burlington"
          },
         "id" : "8b04014a9d6e5dbae542004824",
         "public" : false,
         "type" : "wish_list"
      }
   ],
   "total" : 1
}