{
    "coRegistrant": {
        "email": "janedoe@example.com",
        "firstName": "Jane",
        "lastName": "Doe",
        "role": "Bride"
    },
    "creationDate": "2019-10-18T22:06:28.965Z",
    "currentShippingAddressInfo": {
        "addressId": "home_address",
        "title": "home_address, John Murphy, Burlington"
    },
    "customerProductListItems": [
        {
            "id": "30f35c187ea255ccb633c3ba11",
            "priority": 4,
            "productId": "SimpleProduct",
            "public": false,
            "purchasedQuantity": 0,
            "quantity": 2,
            "type": "product"
        }
    ],
    "description": "our productlist",
    "event": {
        "city": "Washington",
        "country": "US",
        "date": "2019-09-05T17:12:56.670Z",
        "state": "DC",
        "type": "Wedding"
    },
    "id": "bcedkiWbxCM2MaaadkRhB2IBzM",
    "lastModified": "2019-10-18T22:06:28.971Z",
    "name": "OurProductList",
    "public": true,
    "registrant": {
        "email": "johndoe@example.com",
        "firstName": "John",
        "lastName": "Doe",
        "role": "Groom"
    },
    "type": "wish_list"
}