#%RAML 1.0 NamedExample
value:
  {
    "id" : "1d447daa4d25805fd682bd4ce1",
    "priority" : 4,
    "productId" : "RedDress1",
    "public" : true,
    "purchasedQuantity" : 0,
    "quantity" : 2,
    "type" : "product"
  }