#%RAML 1.0 NamedExample
value:
  {
    "authType": "registered",
    "creationDate": "2020-02-14T20:39:53.818Z",
    "customerId": "abfTEMDZOgi3JPrkHjv9IhoziM",
    "customerNo": "00010009",
    "email": "jwild@yourstore.com",
    "enabled": true,
    "fax": "+49 03641 78393 346",
    "firstName": "John",
    "lastLoginTime": "2020-02-14T20:51:59.313Z",
    "lastModified": "2020-02-14T20:55:12.133Z",
    "lastName": "Wild",
    "lastVisitTime": "2020-02-14T20:51:59.313Z",
    "login": "f0a43dc2-692a-43bf-b008-e10918ea935d",
    "previousLoginTime": "2020-02-14T20:51:59.313Z",
    "previousVisitTime": "2020-02-14T20:51:59.313Z"
  }