description: The user has sent too many requests in a given amount of time ("rate limiting")
headers: 
  Retry-After:
    examples:
      after-seconds: "120"
body:
  application/problem+json:
    type: !include ../../dataTypes/error-response.raml
    example:
      type: "https://api.commercecloud.salesforce.com/documentation/error/v1/errors/too-many-requests"
      title: Too Many Requests
      detail: You have performed too many requests in a short period of time.