/*
 * Copyright (c) 2021, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
/**
 * This is a mock config to be used for unit tests
 *
 * By default, a generated project is a single-site and single-locale app
 * However, it can be extended to multi-site with multi-locale easily.
 * To ensure that feature work correctly, we test our code with multi-site config in mind, so we created this mock config.
 * A single-site, single-locale config is a special case of multi-site case.
 */
module.exports = {
    id: '@salesforce/extension-chakra-storefront',
    enabled: true,
    activeDataEnabled: true,
    categoryNav: {
        defaultNavSsrDepth: 1,
        defaultRootCategory: 'root'
    },
    commerceAPI: {
        proxyPath: `/mobify/proxy/api`,
        parameters: {
            clientId: 'c9c45bfd-0ed3-4aa2-9971-40f88962b836',
            organizationId: 'f_ecom_zzrf_001',
            shortCode: '11111111',
            siteId: 'site-1'
        }
    },
    defaultSite: 'site-1',
    defaultAppLocale: 'en-GB',
    defaultSiteTitle: 'Retail React App',
    einsteinAPI: {
        host: 'http://localhost:7777',
        einsteinId: '11111111',
        // This differs from the siteId in commerceAPIConfig for testing purposes
        siteId: 'EinsteinTestSite',
        // Flag Einstein activities as coming from a production environment.
        // By setting this to true, the Einstein activities generated by the environment will appear
        // in production environment reports
        // This is temporary and is meant as a placeholder until there is a mechanism for reading
        // the is_production property from an MRT target
        isProduction: false
    },
    maxCacheAge: 900,
    pages: {
        Account: {
            path: '/account',
            orderSearchParam: {limit: 10, offset: 0, sort: 'best-matches', refine: []}
        },
        Cart: {
            path: '/cart'
        },
        Checkout: {
            path: '/checkout',
            shippingCountryCode: [
                {value: 'CA', label: 'Canada'},
                {value: 'US', label: 'United States'}
            ]
        },
        CheckoutConfirmation: {
            path: '/checkout/confirmation/:orderNo'
        },
        Home: {
            path: '/',
            productLimit: 10,
            mainCategory: 'newarrivals'
        },
        Login: {
            path: '/login'
        },
        Registration: {
            path: '/registration'
        },
        ResetPassword: {
            path: '/reset-password'
        },
        LoginRedirect: {
            path: '/callback'
        },
        ProductDetail: {
            path: '/product/:productId'
        },
        ProductList: {
            path: ['/search', '/category/:categoryId'],
            imageViewType: 'large',
            selectableAttributeId: 'color',
            filterAccordionSate: 'filters-expanded-index'
        }
    },
    search: {
        recentSearchLimit: 5,
        recentSearchKey: 'recent-search-key',
        recentSearchMinLength: 3,
        defaultSearchParams: {limit: 25, offset: 0, sort: 'best-matches', refine: []},
        defaultLimitValues: [25, 50, 100]
    },
    siteAliases: {
        'site-1': 'uk',
        'site-2': 'us'
    },
    sites: [
        {
            id: 'site-1',
            l10n: {
                defaultLocale: 'en-GB',
                defaultCurrency: 'GBP',
                supportedLocales: [
                    {
                        id: 'en-GB',
                        preferredCurrency: 'GBP'
                    },
                    {
                        id: 'fr-FR',
                        alias: 'fr',
                        preferredCurrency: 'EUR'
                    },
                    {
                        id: 'it-IT',
                        preferredCurrency: 'EUR'
                    }
                ]
            }
        },
        {
            id: 'site-2',
            l10n: {
                defaultLocale: 'en-US',
                defaultCurrency: 'USD',
                supportedLocales: [
                    {
                        id: 'en-US',
                        preferredCurrency: 'USD'
                    },
                    {
                        id: 'en-CA',
                        preferredCurrency: 'USD'
                    }
                ]
            }
        }
    ],
    staleWhileRevalidate: 900,
    url: {
        site: 'path',
        locale: 'path',
        showDefaults: true,
        interpretPlusSignAsSpace: false
    }
}
