#%RAML 1.0 Trait
usage: |-
  Traits intended for GET APIs that take a name of a <<type>> field and support
  two query parameters based on that name; one suffixed with `From` that will
  include the passed <<type>> as a lower bound, and one suffixed with `To` that
  will exclude the passed <<type>> as an upper bound.

  ## Parameters:

  name: The name of the field that will be filtered
  type: The type of the field that will be filtered


queryParameters:
  <<name>>From:
    description: If passed, will return records where the `<<name>>` is equal to or greater than the passed `<<type>>`.
    type: <<type>>
    required: false
  <<name>>To:
    description: If passed, will return records where the `<<name>>` is less than the passed `<<type>>`.
    type: <<type>>
    required: false
