#%RAML 1.0
version: v1
title: restful-conventions
baseUri: https://{shortCode}.api.commercecloud.salesforce.com/local/salutation/{version}
securedBy: conventions.GDoT
protocols:
  - HTTPS
mediaType: 
  - application/json
description: A sample API demonstrating how to use the various standards available.

uses:
  conventions: api-standards.raml

types:
  salutation:
    type: object
    properties:
      language: string
      word: string
      languageOrigin?: date-only
      speakers: number
    examples:
      spanish:
        language: es
        word: Hola
        speakers: 100000000
      italian:
        language: it
        word: Ciao
        languageOrigin: 1620-01-30
        speakers: 99999999
      english:
        language: en
        word: Hello
        speakers: 3
      german:
        language: de
        word: Hallo
        speakers: 170000000
    
/salutations:
  get:
    description: Get all salutations
    displayName: getSalutations
    is: 
      - conventions.RateLimited:
          responseStatus: 200
      - conventions.OffsetPaginated:
          defaultSize: 50
          maxLimit: 50
      - conventions.DateRangeFilter:
          name: languageOrigin
      - conventions.NumericRangeFilter:
          name: speakers
    responses:
      200:
        description: successful response
        body:
          application/json:
            type: salutation[]

  post:
    description: Asynchronously create an annotation allowing the server to create an ID for it
    displayName: createSalutation
    is: 
      - conventions.RateLimited:
          responseStatus: 202
      - conventions.AsyncCreated
      - conventions.EtagResponse:
          responseStatus: 202
    body:
      application/json:
        type: salutation
    responses:
        202:
          description: successful response
        405:
          description: Not allowed
          body:
            type: conventions.AbsoluteUrl
          
  /{id}:
    put:
      description: Synchronously create an annotation allowing the server to create an ID for it
      displayName: createSalutationSynchronously
      is: 
        - conventions.RateLimited:
            responseStatus: 201
        - conventions.RateLimited:
            responseStatus: 404
        - conventions.EtagResponse:
            responseStatus: 201
        - conventions.SyncCreated:
            responseType: string
      responses:
        201:
          description: successful response
        404:
          description: Not found
          body:
            application/json:
              type: conventions.ErrorResponse
             

    get:
      description: gets details for a specific salutation
      displayName: getSalutation
      is:
        - conventions.DateConditionalRequest:
            responseStatus: 202
        - conventions.EtagConditionalRequest:
            responseStatus: 202
        - conventions.EtagResponse:
            responseStatus: 202
        - conventions.RateLimited:
            responseStatus: 202
      body:
        application/json:
          type: salutation
          description: successful response
        
