name: SalesforceCommerceCloud/pwa-kit/performance-metrics

on:
    workflow_dispatch: # Allows you to manually run the workflow on any branch.
    schedule:
        # Run every day at 7pm (PST) - cron uses UTC times.
        # We want to run it before the performance tests are scheduled to run.
        # Runs on the default branch.
        - cron: '0 3 * * *'

jobs:
    run-performance-metrics:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: Install Monorepo Dependencies
              run: |-
                  npm ci

            - name: Generate Project
              id: generate_app
              uses: ./.github/actions/generate_app
              with:
                  use_extensibility: false
                  is_private_client: true
                  setup_hybrid: false
                  project_dir: 'storefront'
                  project_id: 'storefront'
                  org_id: 'f_ecom_tbbn_prd'
                  short_code: 'performance-001'
                  client_id: '9629ef22-f8b8-4987-90ac-b815be3940c8'
                  site_id: 'SiteNemesis'
                  instance_url: 'https://zzrf-001.dx.commercecloud.salesforce.com' # this doesn't matter because the OCAPI proxy in Runtime Admin will take precedence

            - name: Add CSP Directives
              run: |-
                  CSP_DIRECTIVES='{
                    "img-src": ["*.sfcc-store-internal.net"],
                    "script-src": ["*.sfcc-store-internal.net"],
                    "connect-src": ["*.sfcc-store-internal.net"]
                  }'
                  echo "$CSP_DIRECTIVES" | node scripts/add-csp-directives.js --config-path "${{ steps.generate_app.outputs.project_path }}/config/default.js"

            - name: Enable Partial Hydration
              run: |-
                  node scripts/update-config.js app.partialHydrationEnabled true --config-path "${{ steps.generate_app.outputs.project_path }}/config/default.js"

            - name: Create MRT credentials file
              uses: './.github/actions/create_mrt'
              with:
                  mobify_user: ${{ secrets.MOBIFY_STG_CLIENT_USER }}
                  mobify_api_key: ${{ secrets.MOBIFY_STG_CLIENT_API_KEY }}

            - name: Push Bundle to MRT
              uses: './.github/actions/push_to_mrt'
              with:
                  CWD: '${{ steps.generate_app.outputs.project_path }}'
                  PROJECT: q4-pwa-perf-develop
                  TARGET: production
                  FLAGS: --wait --cloud-origin https://cloud-testing.mobify-staging.com
