name: SalesforceCommerceCloud/pwa-kit/test
on:
  push:
    branches:
      - convert-salesforcecommercecloud-pwa-kit-to-actions-20221124-150551
jobs:
  testNode14:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |-
          # Explicitly set pipefile policy. This is the default for non-windows, but seems
          # that is needs to be set on windows to fail immediately.
          set -eo pipefail

          cd ${{ inputs.cwd }}

          # Note: Each of these test commands need to be exposed on the monorepo
          # root and *also* on the PWA package. This section is run on both.

          # Ensure bundlesize is in check
          npm run test:max-file-size

          # Always run fast unit tests
          npm run test
        shell: bash
